apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-metrics-label
  name: b2m-nodejs
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: b2m-nodejs
  sessionAffinity: None
  type: ClusterIP
