apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: b2m-nodejs
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: b2m-nodejs
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metricName: http_request_duration_ms_p90
      targetAverageValue: 200
