apiVersion: v1
kind: Service
metadata:
  labels:
    app: podinfo
    name: app-metrics-label
  name: podinfo
spec:
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 9999
    protocol: TCP
    targetPort: grpc
  selector:
    app: podinfo
  sessionAffinity: None
  type: ClusterIP
